Added check and walkaround for DevILs that are build with Allegro-support.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS GGAPI_CURRENT GGAPI_REVISION GGAPI_AGE build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os WIN32_TRUE WIN32_FALSE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SDL_CONFIG SDL_CPPFLAGS SDL_LDFLAGS SDL_CFLAGS SDL_LIBS FT_CONFIG FT_CPPFLAGS FT_LDFLAGS FT2_CFLAGS FT2_LIBS FT2_CONFIG SDLNET_CPPFLAGS SDLNET_LDFLAGS SDLNET_LIB USE_BUILTIN_SDLNET_TRUE USE_BUILTIN_SDLNET_FALSE GL_LIBS BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS DEVIL_CPPFLAGS DEVIL_LDFLAGS LIBOBJS DEVIL_LIBS LOG4CPP_CPPFLAGS LOG4CPP_LDFLAGS DISABLE_NET_TRUE DISABLE_NET_FALSE GG_USE_NET GIGINET_DEP DEBUG_TRUE DEBUG_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS GGAPI_CURRENT GGAPI_REVISION GGAPI_AGE build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os WIN32_TRUE WIN32_FALSE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SDL_CONFIG SDL_CPPFLAGS SDL_LDFLAGS SDL_CFLAGS SDL_LIBS FT_CONFIG FT_CPPFLAGS FT_LDFLAGS FT2_CFLAGS FT2_LIBS FT2_CONFIG SDLNET_CPPFLAGS SDLNET_LDFLAGS SDLNET_LIB USE_BUILTIN_SDLNET_TRUE USE_BUILTIN_SDLNET_FALSE GL_LIBS BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS DEVIL_CPPFLAGS DEVIL_LDFLAGS LIBOBJS DEVIL_LIBS GG_DEVIL_WITH_ALLEGRO GG_NO_ALLEGRO_HACK LOG4CPP_CPPFLAGS LOG4CPP_LDFLAGS DISABLE_NET_TRUE DISABLE_NET_FALSE GG_USE_NET GIGINET_DEP DEBUG_TRUE DEBUG_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1039,6 +1039,8 @@ Optional Features:
   --disable-sdltest       Do not try to compile and run a test SDL program
        --disable-freetypetest  Do not try to compile and run a test FreeType
                           program
+  --disable-allegro-hack  Disable the hack for Allegro-linked DevILs (ignored
+                          if DevIL is not linked against Allegro)
   --disable-net           disables net support (default on)
   --enable-debug          compile with debugging symbols
 
@@ -4419,7 +4421,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4422 "configure"' > conftest.$ac_ext
+  echo '#line 4424 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5531,7 +5533,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5534:" \
+echo "$as_me:5536:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6563,11 +6565,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6566: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6568: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6570: \$? = $ac_status" >&5
+   echo "$as_me:6572: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6796,11 +6798,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6799: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6801: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6803: \$? = $ac_status" >&5
+   echo "$as_me:6805: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6856,11 +6858,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6859: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6861: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6863: \$? = $ac_status" >&5
+   echo "$as_me:6865: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9031,7 +9033,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9034 "configure"
+#line 9036 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9129,7 +9131,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9132 "configure"
+#line 9134 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11306,11 +11308,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11309: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11311: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11313: \$? = $ac_status" >&5
+   echo "$as_me:11315: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11366,11 +11368,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11369: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11371: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11373: \$? = $ac_status" >&5
+   echo "$as_me:11375: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12720,7 +12722,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12723 "configure"
+#line 12725 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12818,7 +12820,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12821 "configure"
+#line 12823 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13645,11 +13647,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13648: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13650: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13652: \$? = $ac_status" >&5
+   echo "$as_me:13654: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13705,11 +13707,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13708: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13710: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13712: \$? = $ac_status" >&5
+   echo "$as_me:13714: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15737,11 +15739,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15740: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15742: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15744: \$? = $ac_status" >&5
+   echo "$as_me:15746: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15970,11 +15972,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15973: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15975: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15977: \$? = $ac_status" >&5
+   echo "$as_me:15979: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16030,11 +16032,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16033: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16035: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16037: \$? = $ac_status" >&5
+   echo "$as_me:16039: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18205,7 +18207,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18208 "configure"
+#line 18210 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18303,7 +18305,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18306 "configure"
+#line 18308 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22573,17 +22575,6 @@ echo "$as_me: error: FreeType is required" >&2;}
 
 fi
 
-### SDL_image check
-
-#dnl can't use sdl-image, ${sdl-image_libdir} would be misinterpreted
-#YG_GET_PATH(sdl_image)
-#AC_CACHE_SAVE
-#XXCPPFLAGS="$CPPFLAGS"
-#CPPFLAGS="$CPPFLAGS $SDL_CFLAGS"
-#AC_CHECK_HEADERS([SDL_image.h],[],[AC_MSG_ERROR([SDL_image.h not found])])
-#AC_CHECK_LIB(SDL_image,IMG_Load,[],[AC_MSG_ERROR([SDL_image is needed])])
-#CPPFLAGS="$XXCPPFLAGS"
-
 ### SDL_net check
 
 
@@ -23810,6 +23801,9 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+/* In some cases DevIL was linked with Allegro,
+which requires the following to be defined */
+void * _mangled_main_address = (void*)0xdeafdead;
 #include <IL/ilut.h>
 int
 main ()
@@ -24082,6 +24076,9 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+/* In some cases DevIL was linked with Allegro,
+which requires the following to be defined */
+void * _mangled_main_address = (void*)0xdeafdead;
 #include <IL/ilut.h>
 #include <src/_vsnprintf.c>
 int
@@ -24134,14 +24131,7 @@ See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
  else
     LIBS="$yg_cv_search_for_libs_broken_DevIL_ILUT $YG_LIBS_BAK"
-    { echo "$as_me:$LINENO: WARNING:
-*** Your DevIL-libraries are broken! They require the \`_vsnprintf' function,
-*** which is called \`vsnprintf' on your system. I have created a wrapper,
-*** so GiGi _should_ compile fine anyway." >&5
-echo "$as_me: WARNING:
-*** Your DevIL-libraries are broken! They require the \`_vsnprintf' function,
-*** which is called \`vsnprintf' on your system. I have created a wrapper,
-*** so GiGi _should_ compile fine anyway." >&2;}
+    DO_BROKEN_DEVIL_WARNING=yes
  fi
 
 
@@ -24161,6 +24151,81 @@ fi`"
 
 CPPFLAGS="$SAVE_CPPFLAGS"
 LIBS="$SAVE_LIBS"
+echo "$as_me:$LINENO: checking whether DevIL was linked with OpenGL support" >&5
+echo $ECHO_N "checking whether DevIL was linked with OpenGL support... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <IL/ilut.h>
+#ifdef ILUT_USE_OPENGL
+I am compiled with OpenGL
+#endif
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "^I am compiled with OpenGL$" >/dev/null 2>&1; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: nope, that's bad!" >&5
+echo "${ECHO_T}nope, that's bad!" >&6
+                   { { echo "$as_me:$LINENO: error: Your libDevIL does not contain support for OpenGL!" >&5
+echo "$as_me: error: Your libDevIL does not contain support for OpenGL!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest*
+
+echo "$as_me:$LINENO: checking whether DevIL was linked with allegro" >&5
+echo $ECHO_N "checking whether DevIL was linked with allegro... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <IL/ilut.h>
+#ifdef ILUT_USE_ALLEGRO
+I am compiled with allegro
+#endif
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "^I am compiled with allegro$" >/dev/null 2>&1; then
+  DEVIL_WITH_ALLEGRO=yes
+echo "$as_me:$LINENO: result: unfortunately, yes" >&5
+echo "${ECHO_T}unfortunately, yes" >&6
+else
+  echo "$as_me:$LINENO: result: no, that's good!" >&5
+echo "${ECHO_T}no, that's good!" >&6
+fi
+rm -f conftest*
+
+if test x$DEVIL_WITH_ALLEGRO = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define GG_DEVIL_WITH_ALLEGRO
+_ACEOF
+
+  GG_DEVIL_WITH_ALLEGRO="#define GG_DEVIL_WITH_ALLEGRO"
+  DO_ALLEGRO_WARNING=yes
+  GG_NO_ALLEGRO_HACK="/* #undef GG_NO_ALLEGRO_HACK */"
+  # Check whether --enable-allegro-hack or --disable-allegro-hack was given.
+if test "${enable_allegro_hack+set}" = set; then
+  enableval="$enable_allegro_hack"
+  if test x$enableval == xno; then
+  DO_ALLEGRO_WARNING=nohack
+  GG_NO_ALLEGRO_HACK="#define GG_NO_ALLEGRO_HACK"
+fi
+fi;
+else
+  GG_DEVIL_WITH_ALLEGRO="/* #undef GG_DEVIL_WITH_ALLEGRO */"
+  GG_NO_ALLEGRO_HACK="/* #undef GG_NO_ALLEGRO_HACK */"
+fi
+
+
 
 ### expat and log4cpp check
 #YG_GET_PATH(expat)
@@ -25360,6 +25425,8 @@ s,@DEVIL_CPPFLAGS@,$DEVIL_CPPFLAGS,;t t
 s,@DEVIL_LDFLAGS@,$DEVIL_LDFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@DEVIL_LIBS@,$DEVIL_LIBS,;t t
+s,@GG_DEVIL_WITH_ALLEGRO@,$GG_DEVIL_WITH_ALLEGRO,;t t
+s,@GG_NO_ALLEGRO_HACK@,$GG_NO_ALLEGRO_HACK,;t t
 s,@LOG4CPP_CPPFLAGS@,$LOG4CPP_CPPFLAGS,;t t
 s,@LOG4CPP_LDFLAGS@,$LOG4CPP_LDFLAGS,;t t
 s,@DISABLE_NET_TRUE@,$DISABLE_NET_TRUE,;t t
@@ -26091,3 +26158,47 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
+if test x$DO_BROKEN_DEVIL_WARNING = xyes; then
+  { echo "$as_me:$LINENO: WARNING:
+*** Your DevIL-libraries are broken! They require the \`_vsnprintf' function,
+*** which is called \`vsnprintf' on your system. I have created a wrapper,
+*** so GiGi _should_ compile fine anyway." >&5
+echo "$as_me: WARNING:
+*** Your DevIL-libraries are broken! They require the \`_vsnprintf' function,
+*** which is called \`vsnprintf' on your system. I have created a wrapper,
+*** so GiGi _should_ compile fine anyway." >&2;}
+fi
+if test x$DO_ALLEGRO_WARNING = xyes; then
+  { echo "$as_me:$LINENO: WARNING:
+*** Your DevIL-library is linked with Allegro, and this
+*** would require placing an \"END_OF_MAIN\"-macro after the program's
+*** main routine. GG contains a hack to remove this requiremnet, but it's
+*** a dirty hack and might not work. Note that you _cannot_ use this GiGi
+*** in Allegro programs!
+*** If you want to be able to use GiGi in Allegro-programs, run configure with
+*** the '--disable-allegro-hack' option." >&5
+echo "$as_me: WARNING:
+*** Your DevIL-library is linked with Allegro, and this
+*** would require placing an \"END_OF_MAIN\"-macro after the program's
+*** main routine. GG contains a hack to remove this requiremnet, but it's
+*** a dirty hack and might not work. Note that you _cannot_ use this GiGi
+*** in Allegro programs!
+*** If you want to be able to use GiGi in Allegro-programs, run configure with
+*** the '--disable-allegro-hack' option." >&2;}
+fi
+if test x$DO_ALLEGRO_WARNING = xnohack; then
+  { echo "$as_me:$LINENO: WARNING:
+*** Your DevIL-library is linked with Allegro, and this
+*** requires placing an \"END_OF_MAIN\"-macro after the program's
+*** main routine. You have chosen to omit the hack that would eliminate this
+*** requirement! This means that _every_ program that uses this library
+*** has to #include <allegro.h> and place END_OF_MAIN() after the main
+*** function." >&5
+echo "$as_me: WARNING:
+*** Your DevIL-library is linked with Allegro, and this
+*** requires placing an \"END_OF_MAIN\"-macro after the program's
+*** main routine. You have chosen to omit the hack that would eliminate this
+*** requirement! This means that _every_ program that uses this library
+*** has to #include <allegro.h> and place END_OF_MAIN() after the main
+*** function." >&2;}
+fi
