New version from Dennis

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1066,7 +1066,7 @@ Optional Packages:
   --with-sdlnet-libdir=DIR
                           specify exact library dir for sdlnet library
   --with-builtin-sdlnet   forces/forbids use of built-in version of SDL_net,
-                          default is autodetect
+                          default is force
   --with-boost=DIR        root directory of boost installation
   --with-boost-include=DIR
                           specify exact include dir for boost headers
@@ -1488,6 +1488,7 @@ ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
 
 
 
@@ -4298,7 +4299,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4301 "configure"' > conftest.$ac_ext
+  echo '#line 4302 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5381,7 +5382,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5384:" \
+echo "$as_me:5385:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6386,11 +6387,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6389: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6390: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6393: \$? = $ac_status" >&5
+   echo "$as_me:6394: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6618,11 +6619,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6621: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6622: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6625: \$? = $ac_status" >&5
+   echo "$as_me:6626: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6685,11 +6686,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6688: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6689: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6692: \$? = $ac_status" >&5
+   echo "$as_me:6693: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8697,7 +8698,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8700 "configure"
+#line 8701 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8795,7 +8796,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8798 "configure"
+#line 8799 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10927,11 +10928,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10930: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10931: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10934: \$? = $ac_status" >&5
+   echo "$as_me:10935: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10994,11 +10995,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10997: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11001: \$? = $ac_status" >&5
+   echo "$as_me:11002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12237,7 +12238,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12240 "configure"
+#line 12241 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12335,7 +12336,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12338 "configure"
+#line 12339 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13157,11 +13158,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13160: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13161: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13164: \$? = $ac_status" >&5
+   echo "$as_me:13165: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13224,11 +13225,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13227: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13228: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13231: \$? = $ac_status" >&5
+   echo "$as_me:13232: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15164,11 +15165,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15167: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15168: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15171: \$? = $ac_status" >&5
+   echo "$as_me:15172: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15396,11 +15397,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15399: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15400: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15403: \$? = $ac_status" >&5
+   echo "$as_me:15404: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15463,11 +15464,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15466: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15467: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15470: \$? = $ac_status" >&5
+   echo "$as_me:15471: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17475,7 +17476,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17478 "configure"
+#line 17479 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17573,7 +17574,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17576 "configure"
+#line 17577 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19859,8 +19860,7 @@ _ACEOF
 
 
 
-
-for ac_func in floor gethostbyaddr gethostbyname memmove memset sqrt
+for ac_func in floor gethostbyaddr gethostbyname memmove memset
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -19942,6 +19942,118 @@ _ACEOF
 
 fi
 done
+
+echo "$as_me:$LINENO: checking for library containing sqrt" >&5
+echo $ECHO_N "checking for library containing sqrt... $ECHO_C" >&6
+if test "${ac_cv_search_sqrt+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_sqrt=no
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sqrt ();
+int
+main ()
+{
+sqrt ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_sqrt="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_sqrt" = no; then
+  for ac_lib in m; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sqrt ();
+int
+main ()
+{
+sqrt ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_sqrt="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_sqrt" >&5
+echo "${ECHO_T}$ac_cv_search_sqrt" >&6
+if test "$ac_cv_search_sqrt" != no; then
+  test "$ac_cv_search_sqrt" = "none required" || LIBS="$ac_cv_search_sqrt $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: The sqrt-function was not found. This is bad!
+See \`config.log' for more details." >&5
+echo "$as_me: error: The sqrt-function was not found. This is bad!
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 # Checks for libraries.
@@ -20320,7 +20432,7 @@ See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-    LIBS=$OLD_LIBS
+    LIBS="$OLD_LIBS"
   else
      # Unix target, we require sdl-config here (at least for now, to eliminate strange linking errors)
 
@@ -21046,7 +21158,7 @@ fi
 
     FT2_CFLAGS=$FT_CPPFLAGS
 
-    FT2_LIBS="-lfreetype $FT2_LDADD"
+    FT2_LIBS="-lfreetype $FT2_LDFLAGS"
 
     OLD_LIBS=$LIBS
     LIBS="$OLD_LIBS $FT2_LIBS"
@@ -21247,7 +21359,7 @@ echo "$as_me: error: Freetype was not found, did you specify the correct paths
    { (exit 1); exit 1; }; }
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-    LIBS=$OLD_LIBS
+    LIBS="$OLD_LIBS"
   else
      # Unix target, we require freetype-config here (at least for now, to eliminate strange linking errors)
 
@@ -21752,6 +21864,8 @@ fi
 if test "${with_builtin_sdlnet+set}" = set; then
   withval="$with_builtin_sdlnet"
 
+else
+  with_builtin_sdlnet=yes
 fi;
 
 if test x$with_builtin_sdlnet = xyes; then
@@ -21997,7 +22111,6 @@ done
 
 
 SAVE_LIBS="$LIBS"
-LIBS=""
  YG_LIBS_BAK="$LIBS"
  echo "$as_me:$LINENO: checking for OpenGl" >&5
 echo $ECHO_N "checking for OpenGl... $ECHO_C" >&6
@@ -22120,10 +22233,10 @@ See \`config.log' for more details." >&2;}
  fi
 
 
-GL_LIBS="$LIBS"
+
+GL_LIBS="`echo "$LIBS"|sed -e \"s@$SAVE_LIBS@@\"`"
 
 LIBS="$SAVE_LIBS"
-
 FAILED=no
 
 cat >confcache <<\_ACEOF
@@ -22184,7 +22297,6 @@ rm -f confcache
 ### Boost check
 
 SAVE_LIBS="$LIBS"
-LIBS=""
 
 # Check whether --with-boost or --without-boost was given.
 if test "${with_boost+set}" = set; then
@@ -22539,7 +22651,7 @@ else
 fi
 
 
-BOOST_LIBS="$LIBS"
+BOOST_LIBS="`echo "$LIBS"|sed -e \"s@$SAVE_LIBS@@\"`"
 
 LIBS="$SAVE_LIBS"
 
@@ -22664,7 +22776,7 @@ fi
 SAVE_LIBS="$LIBS"
 SAVE_CPPFLAGS="$CPPFLAGS"
 # do we need to check for libjpeg, libpng etc?
-LIBS="-lIL -lILU $GL_LIBS $SDL_LIBS"
+LIBS="$GL_LIBS $SDL_LIBS -lIL -lILU"
 CPPFLAGS="$CPPFLAGS $SDL_CFLAGS"
 
 
@@ -22875,7 +22987,7 @@ See \`config.log' for more details." >&2;}
  fi
 
 
-DEVIL_LIBS="$LIBS"
+DEVIL_LIBS="`echo "$LIBS"|sed -e \"s@$SAVE_LIBS@@\"`"
 
 CPPFLAGS="$SAVE_CPPFLAGS"
 LIBS="$SAVE_LIBS"
@@ -22925,6 +23037,7 @@ else
 fi
 
 
+SAVE_LIBS="$LIBS"
 
 echo "$as_me:$LINENO: checking for XML_ParserCreate in -lexpat" >&5
 echo $ECHO_N "checking for XML_ParserCreate in -lexpat... $ECHO_C" >&6
@@ -22995,7 +23108,7 @@ See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
+LIBS="$SAVE_LIBS"
 
 
 # Check whether --with-log4cpp or --without-log4cpp was given.
@@ -23187,8 +23300,10 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: log4cpp/Category.hh not found in include-path" >&5
-echo "$as_me: error: log4cpp/Category.hh not found in include-path" >&2;}
+  { { echo "$as_me:$LINENO: error: log4cpp/Category.hh not found in include-path
+See \`config.log' for more details." >&5
+echo "$as_me: error: log4cpp/Category.hh not found in include-path
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -23264,8 +23379,72 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-if test x$with_builtin_sdlnet = xyes -a $WIN32=yes; then
+if test x$with_builtin_sdlnet = xyes -a $WIN32 = yes; then
   # the windows version of sdlnet needs wsock32 linked in
+
+echo "$as_me:$LINENO: checking for main in -lwsock32" >&5
+echo $ECHO_N "checking for main in -lwsock32... $ECHO_C" >&6
+if test "${ac_cv_lib_wsock32_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lwsock32  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_wsock32_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_wsock32_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_wsock32_main" >&5
+echo "${ECHO_T}$ac_cv_lib_wsock32_main" >&6
+if test $ac_cv_lib_wsock32_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBWSOCK32 1
+_ACEOF
+
+  LIBS="-lwsock32 $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: wsock32 not found!
+See \`config.log' for more details." >&5
+echo "$as_me: error: wsock32 not found!
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
   LIBS="$LIBS -lwsock32"
 fi
 # Check whether --enable-net or --disable-net was given.
